version: "3.7"
services:
  express:
    container_name: express
    build:
      context: ./express
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./express:/usr/app
  graphqlmesh:
    container_name: graphqlmeshtest
    depends_on:
      - redismesh
    build:
      context: ./mesh
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    volumes:
      - ./mesh:/usr/app
  redismesh:
    container_name: redismeshtest
    image: "bitnami/redis:latest"
    ports:
      - "3003:6379"
    environment:
      - REDIS_PASSWORD=redis
    volumes:
      - ./redis/data:/bitnami/redis/data
      - ./redis/conf/overrides.conf:/opt/bitnami/redis/mounted-etc/overrides.conf
