sources:
  - name: AA
    handler:
      jsonSchema:
        endpoint: http://express:3001
        operations:
          - type: Query
            field: user
            path: /user
            method: GET
            responseSample: ./json-samples/user.json
            responseTypeName: User

# transforms:
#   - filterSchema:
#       mode: wrap
#       filters:
#         - User.!password
plugins:
  # - responseCache: {}
  - prometheus:
      requestCount: true
      requestSummary: true
      parse: true
      validate: true
      contextBuilding: true
      execute: true
      errors: true
      # resolvers: true
      deprecatedFields: true
    # endpoint: /metrics
  - httpDetailsExtensions:
      if: "env.NODE_ENV === 'development'"
serve:
  port: 3002
  hostname: 0.0.0.0
cache:
  redis:
    port: "6379"
    # host: "172.18.0.8"
    host: "redismeshtest"
    password: "redis"
